### ISSUE TITLE
Failed tests

### ISSUE THREAD

**Issue by jerrylvx** [Strilanc/honeycomb-boundaries#7]
When I ran the tests, I encountered the following failures:

<img width="1280" alt="Screenshot 2024-07-02 at 9 02 47 PM" src="https://github.com/Strilanc/honeycomb-boundaries/assets/7014034/c8f853db-663b-436e-a98c-64d4d6fe3b30">

I am not sure how to make sense of them. Were they intended to fail?

**Comment by Strilanc** [comment]
This is probably due to a past change in stim's graphlike error search,
where it now refuses to decompose any errors by default.

**Comment by jerrylvx** [comment]
Thanks for the answer!
